leftnav:
- identifier: 9e41e855-80a4-62a4-a777-56f637151317
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 009acf44-9f72-2020-4074-a23428deb8b2
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 780efd90-d744-597b-8325-cac581c26d18
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: e1379556-10d5-9105-bf2d-b7f438d6a180
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: e112d84d-089f-170b-76d1-2eafade85c98
  name: Projects
  pageRef: /pages/projects
  weight: 50
